config/routes.rb
CreateBlog::Application.routes.draw do

  resources :import_files
  devise_for :users, :controllers => {registrations: "registrations"}

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :informations

  resources :posts do
  resources :comments
  end
  root "posts#index"
  get '/about', to: 'pages#about'

  resources :informations do
    collection { post :import }
  end

  get 'update', to: 'informations#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/import_file.rb
class ImportFile < ApplicationRecord
end

app/models/information.rb
  class Information < ActiveRecord::Base
    require 'csv'
    def self.import(file)
      CSV.foreach(file.path, headers: true) do |row|

        information_hash = row.to_hash # exclude the price field
        information = Information.where(id:information_hash["id"])

        if information.count == 1
          information.first.update_attributes(information_hash)
        else
          Information.create!(information_hash)
        end # end if !product.nil?
      end # end CSV.foreach
    end # end self.import(file)
  end # end class

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3}
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find (params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/import_files_controller.rb
class ImportFilesController < ApplicationController
  before_action :set_import_file, only: [:show, :edit, :update, :destroy]

  # GET /import_files
  # GET /import_files.json
  def index
    @import_files = ImportFile.all
  end

  # GET /import_files/1
  # GET /import_files/1.json
  def show
  end

  # GET /import_files/new
  def new
    @import_file = ImportFile.new
  end

  # GET /import_files/1/edit
  def edit
  end

  # POST /import_files
  # POST /import_files.json
  def create
    @import_file = ImportFile.new(import_file_params)

    respond_to do |format|
      if @import_file.save
        format.html { redirect_to @import_file, notice: 'Import file was successfully created.' }
        format.json { render :show, status: :created, location: @import_file }
      else
        format.html { render :new }
        format.json { render json: @import_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /import_files/1
  # PATCH/PUT /import_files/1.json
  def update
    respond_to do |format|
      if @import_file.update(import_file_params)
        format.html { redirect_to @import_file, notice: 'Import file was successfully updated.' }
        format.json { render :show, status: :ok, location: @import_file }
      else
        format.html { render :edit }
        format.json { render json: @import_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /import_files/1
  # DELETE /import_files/1.json
  def destroy
    @import_file.destroy
    respond_to do |format|
      format.html { redirect_to import_files_url, notice: 'Import file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_import_file
      @import_file = ImportFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def import_file_params
      params.require(:import_file).permit(:user_id, :name, :email, :status)
    end
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController

  def index
    @informations = Information.all # find(params[:id])
    #respond_to do |format|
    #format.html
    #format.csv {send_data @informations.to_csv}
    #end
  end

  def import
    begin
    Information.import(params[:file])
    redirect_to informations_path, notice: "Data Records Imported!"
    rescue
    redirect_to informations_path, notice: "Error! Try Again"
    end
    end
end

def show
  @informations = Information.find(params[:id])
end

def new
  @informations = current_user.informations.build
end

def edit
  @informations = Information.all
end

def update
  if @informations.update(params[:information].permit(:id, :name, :email, :status))
    redirect_to @informations
  else
    render 'edit'
  end

  def destroy
    @informations.destroy
    redirect_to informations_path
  end
  private

  def information_params
    params.require(:information).permit(:id, :name, :email, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def index
    if user_signed_in?
      redirect_to posts_path
    else
      redirect_to new_user_session_path
    end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = current_user.posts.build
  end

  def show
  end

  def create
    @post = current_user.posts.build(post_params)
 respond_to do |format|
    if @post.save
      format.html {redirect_to @post, notice: 'Post was successfully created!'}
      format.json {render :show, status::created, location: @post}
    else
      format.html {render :new}
      format.json {render json: @post.errors, status: :unprocessable_entity}
    end
  end
end
  def edit
  end

  def update
    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  def sign_up_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/import_files_helper.rb
module ImportFilesHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
<div class="comment_content">

    <h4 class="comment_name">Commented by: <strong><%= comment.name %></strong></h4><br>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>

  <% if current_user %>
      <p><%= link_to "Delete", [comment.post, comment],
                     method: :delete,
                     class: "button",
                     data: { confirm: 'Are you sure?' } %></p>
  <% end %>
</div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
  <%= f.label :name %> <br>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :body %> <br>
  <%= f.text_area :body %> <br>
</p>
<br>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/import_files/_form.html.erb
<%= form_with(model: import_file, local: true) do |form| %>
  <% if import_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(import_file.errors.count, "error") %> prohibited this import_file from being saved:</h2>

      <ul>
      <% import_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :name %> <br>
    <%= form.text_field :name, id: :import_file_name %>
  </div>

  <div class="field">
    <%= form.label :email %> <br>
    <%= form.text_field :email, id: :import_file_email %>
  </div>

  <div class="field">
    <%= form.label :status %> <br>
    <%= form.text_field :status, id: :import_file_status %>
  </div>
<br>
  <div class="actions">
    <%= form.submit "Create Employee" %>
  </div>
<% end %>

app/views/import_files/edit.html.erb
<h1>Editing Import File</h1>

<%= render 'form', import_file: @import_file %>

<%= link_to 'Show', @import_file %> |
<%= link_to 'Back', import_files_path %>

app/views/import_files/index.html.erb
<h3>Import Files</h3>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Email</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @import_files.each do |import_file| %>
      <tr>
        <td><%= import_file.user_id %></td>
        <td><%= import_file.name %></td>
        <td><%= import_file.email %></td>
        <td><%= import_file.status %></td>
        <td><%= link_to 'Show', import_file %></td>
        <td><%= link_to 'Edit', edit_import_file_path(import_file) %></td>
        <td><%= link_to 'Destroy', import_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Import File', new_import_file_path %>

app/views/import_files/new.html.erb
<h3>New Import File</h3>

<%= render 'form', import_file: @import_file %>

<%= link_to 'Back', import_files_path %>

app/views/import_files/show.html.erb
<p>
  <strong>User:</strong>
  <%= @import_file.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @import_file.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @import_file.email %>
</p>

<p>
  <strong>Status:</strong>
  <%= @import_file.status %>
</p>

<%= link_to 'Edit', edit_import_file_path(@import_file) %> |
<%= link_to 'Back', import_files_path %>

app/views/informations/import.html.erb
<h1>Informations#import</h1>
<p>Find me in app/views/informations/import.html.erb</p>

app/views/informations/index.html.erb
<h4>Import Files To Dashboard</h4>
<br>
<table class="striped">
  <thead>
  <tr>
    <th>User ID</th>
    <th>Name</th>
    <th>Email</th>
    <th>Status</th>
  </tr>
  </thead>
  <tbody>
  <% @informations.each do |information| %>
      <tr>
        <td><%= information.id %></td>
        <td><%= information.name %></td>
        <td><%= information.email %></td>
        <td><%= information.status %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<div>
  <br><br><br><br><br>
  <h5>Import CSV File</h5>
  <br>
  <%= form_tag import_informations_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import CSV" %>
  <% end %>
</div>
<br><br>
<div> <h5>Download File: </h5>
<%= link_to 'CSV', informations_path(format: 'CSV') %> |
  <%= link_to 'Excel', informations_path(format: 'xls') %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DashBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>

    <div id="sidebar">
      <div id="logo">
      <%= link_to root_path do %>
            <%= image_tag "Home_Button.jpg" %>
      <% end %>
      </div>

  <ul>
    <li class="category">Categories</li>
    <li><%= link_to "Introduction", about_path%></li>
    <li><%= link_to "Dashboard", root_path %></li>
    <li><%= link_to "Import Files", import_files_path%></li>
  </ul>

  <ul>
    <li class="category">Social Links</li>
    <li><a href="https://google.com">Google</a></li>
    <li><a href="http://youtube.com">Youtube</a></li>
    <li><a href="mailto:jay.pham1989@gmail.com">Email</a></li>
  </ul>
      <br> <br><br>
<ul>
  <div class="buttons">
      <% if !user_signed_in? %>
        <button class="button"> <%= link_to 'Create Account', new_user_registration_path %></button><br>
        <button class="button"> <%= link_to 'Sign In', new_user_session_path %></button>
      <% end %>
  </div>
</ul>
    </div>

    <div id="main_content">
      <div class="navbar-fixed">
      <div id="header">

       <% if current_page?(root_path) %>
        <p>All Posts</p>
       <% elsif current_page?(about_path) %>
        <p>Introduction</p>
            <% elsif current_page?(import_files_path)%>
            <p> Import CSV Files Page</p>
       <% else %>
        <%= link_to 'Back to All Posts', root_path %>
        <% end %>


        <% if user_signed_in? %>
        <div class="buttons">
          <p> Hello, <%= current_user.name %></p>
          <button class="button"><%= link_to current_user.email, edit_user_registration_path %></button>
          <button class="button"><%= link_to 'New Post', new_post_path %></button>
          <button class="button"><%= link_to 'Sign Out',  destroy_user_session_path, :method => 'delete' %></button>
        </div>
            </div>

      <% end %>

      </div>

      <div id="page_wrapper">

      <% flash.each do |name, msg| %>
         <%= content_tag(:div, msg, class: "alert") %>
         <% end %>

      <%= yield %>
      </div>
    </div>
</body>
</html>

app/views/pages/about.html.erb
<div class=post_wrapper''>
  <div id="profile_image">
    <%= image_tag "profile.jpg"%>
  </div>

  <div id="content">
    <h1> Hi, Welcome</h1>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div id="errors">
          <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <br>
    <%= f.label :body %><br>
    <%= f.text_area :body %><br>
    <br>
    <%= f.submit "Create Post"%>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h2>Edit Post</h2>

  <%= render'form'%>

</div>

app/views/posts/index.html.erb
<div id="post_content">
  <h4> Discussion Board</h4>

<p id="notice"%></p>
  <table class="striped">
    <tbody>
    <tr>
<% @posts.each do |post| %>
<div class="post_wrapper">
  <h2 class="title"> <%= link_to post.title, post %></h2>
  <p class="date">Published at: <%= post.created_at.strftime ("%B, %d, %Y") %></p>
  <p class="user">Created by:  <%= link_to post.user.name %></p>
</div>
     <%end%>
  </tbody>
  </tr>
  </table>
</div>

app/views/posts/new.html.erb
<div id="page_wrapper">
<h4>New Post</h4>
<%= render 'form'%>
</div>

app/views/posts/show.html.erb
<div id="post_content">
<div class="post_wrapper">
  <h4><%= @post.title %></h4>
  <p class="date">
  <p>Submitted <%= time_ago_in_words(@post.created_at) %> Ago <br /></p>

  <div class="buttons">
    <% if current_user == @post.user %>
        <button class="button"> <%= link_to 'Edit', edit_post_path(@post) %> </button> ||
        <button class="button"> <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %> </button>
    <% end %>
  </div>

 <h6> <p class="body"><%= @post.body %></p></h6>
</div>
  <div id="comments">
    <h5><%= @post.comments.count %> Comments</h5>
    <%= render @post.comments %>
<% if user_signed_in? %>
    <h5>Add a comment:</h5>
    <%= render "comments/form" %>
        <% end %>
  </div>
</div>